{% set name = "openff-toolkit" %}
{% set version = "0.11.4" %}

package:
  name: openff-toolkit-split
  version: {{ version }}

source:
  - path: ./build_base.sh
  - url: https://github.com/openforcefield/openff-toolkit/archive/{{ version }}.tar.gz
    sha256: 361fdee66b50fd167ad275f1a85707530c7c571b4d3e8c7143da3c55b8384ab2

build:
  number: 0

outputs:
  - name: openff-toolkit-base
    script: build_base.sh
    build:
      noarch: python

    requirements:
      host:
        - python >=3.8
        - pip
      run:
        - python >=3.8
        - packaging
        - numpy
        - smirnoff99frosst
        - openff-forcefields
        - openff-amber-ff-ports >=0.0.3
        - openff-units >=0.2.0
        - openff-utilities
        - networkx >=2.5
        - xmltodict
        - importlib-metadata >=4.10
        - python-constraint
        - cachetools
        - cached-property
      run_constrained:
        - openforcefield ==9999999999

    test:
      imports:
        - openff.toolkit

  - name: openff-toolkit
    build:
      noarch: python

    requirements:
      host:
        - python >=3.8
      run:
        - python >=3.8
        - openmm >=7.6
        - openff-interchange >=0.2.0
        - rdkit
        - ambertools >=20
        - mdtraj
        - {{ pin_subpackage('openff-toolkit-base', exact=True) }}
        - notebook
        - ipywidgets =7

    test:
      imports:
        - openff.toolkit
        - rdkit
      files:
        - test_openff_toolkit.py
      commands:
        - python test_openff_toolkit.py

  - name: openff-toolkit-examples
    script: move-examples.sh
    build:
      noarch: python

    requirements:
      run:
        - python >=3.8
        - nglview
        - notebook
        - qcelemental
        - qcportal
        - qcengine
        - openmmforcefields  # Expected to bring in 0.11.2, add constraint if this is an issue
        - {{ pin_subpackage('openff-toolkit', exact=True) }}

    test:
      files:
        - test_examples_copied.py
      source_files:
        - examples
      commands:
        - python test_examples_copied.py

about:
  home: https://openforcefield.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A modern, extensible library for molecular mechanics force field science from the Open Force Field Initiative
  description: |
    The Open Force Field Toolkit, built by the Open Force Field Initiative, is a Python
    toolkit for the development and application of modern molecular mechanics force fields
    based on direct chemical perception and rigorous statistical parameterization methods.
  doc_url: https://open-forcefield-toolkit.readthedocs.io/
  dev_url: https://github.com/openforcefield/openff-toolkit

extra:
  recipe-maintainers:
    - jaimergp
    - j-wags
    - mattwthompson
