{% set name = "openff-toolkit" %}
{% set version = "0.15.0" %}

package:
  name: openff-toolkit-split
  version: {{ version }}

source:
  - path: ./build_base.sh
  - url: https://github.com/openforcefield/openff-toolkit/archive/{{ version }}.tar.gz
    sha256: bc72a4b5e697029c5747446a94201a05fae6149d8ae6dac171eced08c4b6d059

build:
  number: 0

outputs:
  - name: openff-toolkit-base
    script: build_base.sh
    build:
      noarch: python

    requirements:
      host:
        - python >=3.9,<3.12
        - pip
      run:
        - python >=3.9
        - packaging
        - numpy =1
        - smirnoff99frosst
        - openff-forcefields
        - openff-amber-ff-ports >=0.0.4
        - openff-units >=0.2.0
        - openff-units >=0.2.1
        - openff-utilities
        - networkx >=2.5
        - xmltodict
        - bson
        - importlib-metadata >=4.10
        - python-constraint
        - cachetools
        - cached-property
        - typing_extensions
      run_constrained:
        - openforcefield ==9999999999
        - pydantic <3.0.0a0
        - qcportal >=0.50.0

    test:
      imports:
        - openff.toolkit

  - name: openff-toolkit
    build:
      noarch: python

    requirements:
      host:
        - python >=3.9,<3.12
      run:
        - python >=3.9
        - openmm >=7.6
        - openff-interchange >=0.3.17
        - rdkit
        - ambertools >=22
        - mdtraj
        - {{ pin_subpackage('openff-toolkit-base', exact=True) }}
        - notebook
        - ipywidgets

    test:
      imports:
        - openff.toolkit
        - rdkit
      files:
        - test_openff_toolkit.py
      commands:
        - python test_openff_toolkit.py

  - name: openff-toolkit-examples
    script: move-examples.sh
    build:
      noarch: python

    requirements:
      run:
        - python >=3.9
        - nglview
        - notebook
        - openff-nagl >=0.3.1
        - qcelemental
        - qcportal <0.50
        - qcengine
        - openmmforcefields 
        - pdbfixer
        - {{ pin_subpackage('openff-toolkit', exact=True) }}
      run_constrained:
        # QCPortal has not been updated to work with Pydantic 2
        - pydantic =1

    test:
      files:
        - test_examples_copied.py
      source_files:
        - examples
      commands:
        - python test_examples_copied.py

about:
  home: https://openforcefield.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A modern, extensible library for molecular mechanics force field science from the Open Force Field Initiative
  description: |
    The Open Force Field Toolkit, built by the Open Force Field Initiative, is a Python
    toolkit for the development and application of modern molecular mechanics force fields
    based on direct chemical perception and rigorous statistical parameterization methods.
  doc_url: https://open-forcefield-toolkit.readthedocs.io/
  dev_url: https://github.com/openforcefield/openff-toolkit

extra:
  recipe-maintainers:
    - jaimergp
    - j-wags
    - mattwthompson
