{% set name = "openff-toolkit" %}
{% set version = "0.10.0" %}

package:
  name: openff-toolkit-split
  version: {{ version }}

source:
  - path: ./build_base.sh
  - url: https://github.com/openforcefield/openff-toolkit/archive/{{ version }}.tar.gz
    sha256: b15aec2b0d4ae6384d96a6b53178a22be95ac39760b3a534ba740463eb819a27

build:
  number: 0

outputs:
  - name: openff-toolkit-base
    script: build_base.sh
    build:
      noarch: python

    requirements:
      host:
        - python >=3.6
        - pip
      run:
        - python >=3.6
        - packaging
        - numpy
        - smirnoff99frosst
        - openff-forcefields
        - openmm
        - networkx >=2.5
        - mdtraj
        - xmltodict
      run_constrained:
        - openforcefield ==9999999999

    test:
      imports:
        - openff.toolkit

  - name: openff-toolkit
    build:
      noarch: python

    requirements:
      host:
        - python >=3.6
      run:
        - python >=3.6
        - rdkit
        - ambertools >=20
        - {{ pin_subpackage('openff-toolkit-base', exact=True) }}

    test:
      imports:
        - openff.toolkit
        - rdkit
      files:
        - test_openff_toolkit_base.py
      commands:
        - python test_openff_toolkit_base.py

  - name: openff-toolkit-examples
    script: move-examples.sh
    build:
      noarch: python

    requirements:
      run:
        - python >=3.6
        - nglview
        - notebook
        - qcelemental
        - qcportal
        - qcengine
        - openmmforcefields
        - {{ pin_subpackage('openff-toolkit', exact=True) }}

    test:
      files:
        - test_examples_copied.py
      source_files:
        - examples
      commands:
        - python test_examples_copied.py

about:
  home: https://openforcefield.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A modern, extensible library for molecular mechanics force field science from the Open Force Field Initiative
  description: |
    The Open Force Field Toolkit, built by the Open Force Field Initiative, is a Python
    toolkit for the development and application of modern molecular mechanics force fields
    based on direct chemical perception and rigorous statistical parameterization methods.
  doc_url: https://open-forcefield-toolkit.readthedocs.io/
  dev_url: https://github.com/openforcefield/openff-toolkit

extra:
  recipe-maintainers:
    - jaimergp
    - j-wags
    - mattwthompson
